version: '3.9'

services:
  web:
    build:
      context: web
    container_name: web
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./web/app:/var/www/html
      # - ./web/logs:/var/log/apache2
      - ./web/conf/php.ini:/usr/local/etc/php/php.ini
    ports: 
      - '8080:80'
    restart: unless-stopped
    networks:
      - wp
  php-my-admin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
        - "8888:80"
    environment:
        PMA_ARBITRARY: 1
    networks:
      - wp
  db:
    image: mariadb:lts
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=!root1234
      - MARIADB_DATABASE=wp
      - TZ=Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - wp

networks:
  wp: